### ISSUE TITLE
The domain has expired and is currently set to clientHold (DNS won't resolve)

### ISSUE THREAD

**Issue by israelroldan** [montagejs/collectionsjs.com#48]
Apparently, the domain expired yesterday and GANDI has set it to `clientHold`.

Gandi does not allow domains to be renewed by someone else, otherwise, I'd have gladly done so. Can someone look into this?

cc @marchant @kriskowal @hthetiot

**Comment by kriskowal** [comment]
@stuk

**Comment by Stuk** [comment]
Renewed. Should come back in a bit. Sorry!

**Comment by israelroldan** [comment]
It is back! thanks @Stuk @kriskowal
